### ISSUE TITLE
running pipeline error

### ISSUE THREAD

**Issue by ukolesnikova** [PengNi/deepsignal3#3]
Dear all, 

I was trying to run this command 
CUDA_VISIBLE_DEVICES=0 deepsignal3 --pod5 call_mods --input_path pods/pod5/ --bam TE11.bam --model_path ..
/nanopore_2/deepsignal3/model/plant_r1041_5khz_C_epoch4.ckpt --result_file TE11.5mC.call_mods.tsv --nproc 30 --nproc_gpu 6 --seq_len 13 --signal_len 15 --motifs C

but received an error message. I tried to reinstall cuda and pytorch in another environment again, but it did not help. Do you have an idea where is it coming from and how to fix it?

```
# ===============================================
2024-09-02 15:31:48 - INFO - [call_mods] starts
2024-09-02 15:40:30 - INFO - parse the motifs string 
Traceback (most recent call last):
  File "/home/ukolesnikova/.conda/envs/deepsignal2_attempt2/bin/deepsignal3", line 33, in <module>
    sys.exit(load_entry_point('deepsignal3==0.1.1', 'console_scripts', 'deepsignal3')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ukolesnikova/.conda/envs/deepsignal3_attempt2/lib/python3.12/site-packages/deepsignal3-0.1.1-py3.12.egg/deepsignal3/deepsignal3.py", line 1240, in main
    args.func(args)
  File "/home/ukolesnikova/.conda/envs/deepsignal3_attempt2/lib/python3.12/site-packages/deepsignal3-0.1.1-py3.12.egg/deepsignal3/deepsignal3.py", line 43, in main_call_mods
    call_mods(args)
  File "/home/ukolesnikova/.conda/envs/deepsignal3_attempt2/lib/python3.12/site-packages/deepsignal3-0.1.1-py3.12.egg/deepsignal3/call_modifications.py", line 916, in call_mods
    _call_mods_from_pod5_gpu(
  File "/home/ukolesnikova/.conda/envs/deepsignal3_attempt2/lib/python3.12/site-packages/deepsignal3-0.1.1-py3.12.egg/deepsignal3/call_modifications.py", line 644, in _call_mods_from_pod5_gpu
    nproc_ex = nproc - nproc_dp - 1
                       ^^^^^^^^
UnboundLocalError: cannot access local variable 'nproc_dp' where it is not associated with a value
```

**Comment by xyfltq** [comment]
Hi @ukolesnikova , thanks very much for using our tool. The reason for this issue may be that you are not using the GPU properly. Currently, I have updated the code to add detection to avoid similar errors from happening again.

**Comment by ukolesnikova** [comment]
Hi @xyfltq, thank you! There was an issue with pytorch not detecting cuda. Solved it, seems to work
